#!/bin/bash

#   sariug
#   Current Update : 26.06.2019
#
source progress_bar.sh

#OPENMPI=openmpi-2.1.0
setup_scroll_area

# ===================LIBRARY PATHS=========================
CWD="$PWD"
INSTALL_FOLDER="$PWD/install"
DEPENDENCY_FOLDER="$PWD/dependencies"
SDL2="$DEPENDENCY_FOLDER/SDL2-2.0.9"
VTK="$DEPENDENCY_FOLDER/VTK-8.2.0"
GLM="$DEPENDENCY_FOLDER/glm-0.9.7.0"
GLFW3="$DEPENDENCY_FOLDER/glfw-3.2"
CORRADE="$DEPENDENCY_FOLDER/corrade"
MAGNUM="$DEPENDENCY_FOLDER/magnum"
MAGNUM_INTEGRATION="$DEPENDENCY_FOLDER/magnum-integration"
MAGNUM_EXAMPLES="$DEPENDENCY_FOLDER/magnum-examples"
VRPN="$DEPENDENCY_FOLDER/vrpn"
SYNCH="$DEPENDENCY_FOLDER/synch_fixed/synch"
# ===================LIBRARY PATHS=========================
draw_progress_bar 0
# With the order of dependency
# ===================SDL2 =================================
if [ ! -d "$SDL2/build" ]; then
    cd $SDL2
    mkdir build
    cd build
    cmake .. -DCMAKE_INSTALL_PREFIX="$INSTALL_FOLDER"
    draw_progress_bar 4
    make -j3
    draw_progress_bar 8
    make install
    echo -e "\e[46mSDL2 IS FINISHED\e[0m"
    else 
    echo -e "\e[45mSDL2 was built.\e[0m"
fi
# ===================SDL2 =================================
draw_progress_bar 12
# ====================GLM =================================
if [ ! -d "$GLM/build" ]; then
    echo -e "\e[41mGLM IS BUILDING\e[0m"
    cd $GLM
    mkdir build
    cd build
    cmake .. -DCMAKE_INSTALL_PREFIX="$INSTALL_FOLDER"
    make install
    echo -e "\e[46mGLM IS FINISHED\e[0m"
else
    echo -e "\e[45mGLM was built.\e[0m"
fi
# ====================GLM =================================
draw_progress_bar 14
# ====================GLFW3 ===============================
if [ ! -d "$GLFW3/build" ]; then
    echo -e "\e[41mGLFW IS BUILDING\e[0m"
    cd $GLFW3
    mkdir build
    cd build
    cmake .. -DCMAKE_INSTALL_PREFIX="$INSTALL_FOLDER"
    make install
    echo -e "\e[46mGLFW IS FINISHED\e[0m"
else
    echo -e "\e[45mGLFW was built.\e[0m"

fi
# ====================GLFW3 ===============================
draw_progress_bar 18
# # openmpi
# cd ../../$OPENMPI
# ./configure --prefix="$INSTALL_FOLDER"
# make all install 
# ====================VTK =================================
if [ ! -d "$VTK/build" ];then
echo -e "\e[41mVTK IS BUILDING\e[0m"
    cd $VTK
    mkdir build
    cd build
    cmake .. -DCMAKE_INSTALL_PREFIX="$INSTALL_FOLDER"
    draw_progress_bar 21
    make -j3
    draw_progress_bar 35
    make install
else
    echo -e "\e[45mVTK was built.\e[0m"
fi
# ====================VTK =================================
draw_progress_bar 45
# ====================CORRADE =============================
if [ ! -d "$CORRADE/build" ];then
echo -e "\e[41mCorrade IS BUILDING\e[0m"
cd $CORRADE
mkdir build
cd build
cmake .. \
    -DCMAKE_INSTALL_PREFIX="$INSTALL_FOLDER" \
    -DWITH_INTERCONNECT=ON \
    -DWITH_PLUGINMANAGER=ON \
    -DWITH_TESTSUITE=ON
make install
echo -e "\e[46mCorrade IS FINISHED\e[0m"
else
    echo -e "\e[45mCorrade was built.\e[0m"
fi
# ====================CORRADE ===============================
draw_progress_bar 53
# ====================MAGNUM=================================
if [ ! -d "$MAGNUM/build" ];then
echo -e "\e[41mMAGNUM IS BUILDING\e[0m"
# magnum
cd $MAGNUM && mkdir build && cd build
cmake .. \
    -DCMAKE_INSTALL_PREFIX="$INSTALL_FOLDER" \
    -DCMAKE_PREFIX_PATH="$INSTALL_FOLDER" \
    -DCORRADE_INCLUDE_DIR="$INSTALL_FOLDER/include"\
    -DWITH_GLFWAPPLICATION=ON \
    -DWITH_SDL2APPLICATION=ON
make install
echo -e "\e[46mMAGNUM IS FINISHED\e[0m"
else
    echo -e "\e[45mmagnum was built.\e[0m"
fi
# ====================MAGNUM=================================
draw_progress_bar 61
# ====================MAGNUM-INTEGRATION=====================
if [ ! -d "$MAGNUM_INTEGRATION/build" ];then
echo -e "\e[41mMAGNUM INTEGRATION IS BUILDING\e[0m"
# magnum integration
cd $MAGNUM_INTEGRATION
mkdir build 
cd build
cmake .. \
    -DCMAKE_INSTALL_PREFIX="$INSTALL_FOLDER" \
    -DCMAKE_PREFIX_PATH="$INSTALL_FOLDER" \
    -D_CORRADE_MODULE_DIR="$INSTALL_FOLDER/share/cmake/Corrade" \
    -DIMGUI_DIR="$DEPENDENCY_FOLDER/imgui" \
    -DWITH_IMGUI=ON 
make install
echo -e "\e[46mMAGNUM INTEGRATION IS FINISHED\e[0m"
else
    echo -e "\e[45mmagnum-integration was built.\e[0m"
fi
# ====================MAGNUM-INTEGRATION=====================
draw_progress_bar 66
# ====================MAGNUM-EXAMPLES =======================
if [ ! -d "$MAGNUM_EXAMPLES/build" ];then
cd $MAGNUM_EXAMPLES
mkdir build
cd build
cmake .. \
    -DCMAKE_INSTALL_PREFIX="$INSTALL_FOLDER" \
    -DCMAKE_PREFIX_PATH="$INSTALL_FOLDER" \
    -D_CORRADE_MODULE_DIR="$INSTALL_FOLDER/share/cmake/Corrade" \
    -DIMGUI_DIR="$DEPENDENCY_FOLDER/imgui" \
    -DWITH_IMGUI_EXAMPLE=ON\
    -DWITH_TRIANGLE_EXAMPLE=OFF
make install
else
    echo -e "\e[45mmagnum-examples was built.\e[0m"
fi
# ====================MAGNUM-EXAMPLES =======================
draw_progress_bar 70
# =========================VRPN==============================
# Make VRPN
if [ ! -d "$VRPN/build" ];then
cd ../../vrpn
mkdir build
cd build 
cmake -DCMAKE_INSTALL_PREFIX=$INSTALL_FOLDER .. 
draw_progress_bar 73
make -j
make install 
echo -e "\e[46mvrpn IS FINISHED\e[0m"
else
    echo -e "\e[45mVRPN was built.\e[0m"
fi
# =========================VRPN==============================
draw_progress_bar 77
# =========================SYNCH=============================
if [ ! -d "$SYNCH/build" ];then
echo -e "\e[41mSynch INTEGRATION IS BUILDING\e[0m"
cd $SYNCH
mkdir build
cd build
cmake .. \
    -DCMAKE_INSTALL_PREFIX="$INSTALL_FOLDER" \
    -DCMAKE_PREFIX_PATH="$INSTALL_FOLDER" \
    -DVRPN_ROOT_DIR="$INSTALL_FOLDER/lib/vrpn"

make install
echo -e "\e[46msynch IS FINISHED\e[0m"
else
    echo -e "\e[45mSYNCH was built.\e[0m"
fi
# =========================SYNCH=============================
draw_progress_bar 83
# =========================MPFLUID===========================
if [ ! -d "$CWD/mpfluid_vis_sari/build" ];then
echo -e "\e[41mmpfluid_vis_sari INTEGRATION IS BUILDING\e[0m"
# Make MPfluid
cd $CWD/mpfluid_vis_sari
mkdir build
cd build
cmake ../src \
    -DCMAKE_INSTALL_PREFIX="$INSTALL_FOLDER"/mpfluid \
    -DCMAKE_PREFIX_PATH="$INSTALL_FOLDER" \
    -DUSE_HDF5=OFF\
    -DBUILD_HDF_CLIENT=OFF\
    -Dsynch_DIR=$INSTALL_FOLDER/"cmake" \
    -DUSE_SDL2=OFF\
    -D_CORRADE_MODULE_DIR="$INSTALL_FOLDER/share/cmake/Corrade" \
    -DBUILD_SW_CLIENT=OFF\
    -DUSE_SWCOLLECTOR=ON\
    -DUSE_VTK=ON\
    -DBUILD_SW_CLIENT=ON\
    -DBUILD_SCENOGRAPH_PROJECT=ON\
    -DImGui_INCLUDE_DIR="$DEPENDENCY_FOLDER/imgui" 
draw_progress_bar 88
make 
draw_progress_bar 96
make install
cd $INSTALL_FOLDER/bin
chmod +x start_*
else
    echo -e "\e[45mmp_fluid was built.\e[0m"
fi
# =========================MPFLUID===========================
echo -e "\e[44mBuilding libraries finished\e[0m"
draw_progress_bar 99
if [[ $LD_LIBRARY_PATH == *"$INSTALL_FOLDER/lib"* ]]; then
    echo "No need for .bash update"
else
    echo "export LD_LIBRARY_PATH=:$INSTALL_FOLDER/lib:$LD_LIBRARY_PATH">> ~/.bashrc
fi
destroy_scroll_area
