#!/bin/bash

#   sariug
#   Current Update : 26.06.2019
#
source progress_bar.sh

GLFW3=3.2
GLM=0.9.7.0
OPENMPI=openmpi-2.1.0
VTK=VTK-8.2.0
setup_scroll_area

CWD="$PWD"
INSTALL_FOLDER="$PWD/install"
DEPENDENCY_FOLDER="$PWD/dependencies"
draw_progress_bar 0
# With the order of dependency
if [ ! -d "dependencies/SDL2-2.0.9/build" ]; then
    cd dependencies/SDL2*
    mkdir build
    cd build
    cmake .. -DCMAKE_INSTALL_PREFIX="$INSTALL_FOLDER"
    draw_progress_bar 4
    make -j3
    draw_progress_bar 8
    make install
    echo -e "\e[46mSDL2 IS FINISHED\e[0m"
    cd ../../glm*
    else 
    echo -e "\e[45mSDL2 was built.\e[0m"
    cd dependencies/glm*
fi
draw_progress_bar 12
echo -e "\e[41mGLM IS BUILDING\e[0m"
# glm
cd ../../glm*
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX="$INSTALL_FOLDER"
make install
echo -e "\e[46mGLM IS FINISHED\e[0m"
draw_progress_bar 14
echo -e "\e[41mGLFW IS BUILDING\e[0m"
# glwf
cd ../../glfw-$GLFW3
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX="$INSTALL_FOLDER"
make install
draw_progress_bar 18
# # openmpi
# cd ../../$OPENMPI
# ./configure --prefix="$INSTALL_FOLDER"
# make all install 
echo -e "\e[46mGLFW IS FINISHED\e[0m"

if [ ! -d "../../$VTK/build" ];then
echo -e "\e[41mVTK IS BUILDING\e[0m"
# vtk
cd ../../$VTK/build
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX="$INSTALL_FOLDER"
draw_progress_bar 21
make -j3
draw_progress_bar 35
make install
else
    echo -e "\e[45mVTK was built.\e[0m"
fi
draw_progress_bar 45
# corrade
echo -e "\e[41mCorrade IS BUILDING\e[0m"
cd ../../corrade
mkdir build
cd build
cmake .. \
    -DCMAKE_INSTALL_PREFIX="$INSTALL_FOLDER" \
    -DWITH_INTERCONNECT=ON \
    -DWITH_PLUGINMANAGER=ON \
    -DWITH_TESTSUITE=ON
make install
echo -e "\e[46mCorrade IS FINISHED\e[0m"
draw_progress_bar 53
echo -e "\e[41mMAGNUM IS BUILDING\e[0m"
# magnum
cd ../../magnum
mkdir build
cd build
cmake .. \
    -DCMAKE_INSTALL_PREFIX="$INSTALL_FOLDER" \
    -DCMAKE_PREFIX_PATH="$INSTALL_FOLDER" \
    -DCORRADE_INCLUDE_DIR="$INSTALL_FOLDER/include"\
    -DWITH_GLFWAPPLICATION=ON \
    -DWITH_SDL2APPLICATION=ON
make install
echo -e "\e[46mMAGNUM IS FINISHED\e[0m"
draw_progress_bar 61

echo -e "\e[41mMAGNUM INTEGRATION IS BUILDING\e[0m"
# magnum integration
cd ../../magnum-integration
mkdir build 
cd build
cmake .. \
    -DCMAKE_INSTALL_PREFIX="$INSTALL_FOLDER" \
    -DCMAKE_PREFIX_PATH="$INSTALL_FOLDER" \
    -D_CORRADE_MODULE_DIR="$INSTALL_FOLDER/share/cmake/Corrade" \
    -DIMGUI_DIR="$DEPENDENCY_FOLDER/imgui" \
    -DWITH_IMGUI=ON 
make install
echo -e "\e[46mMAGNUM INTEGRATION IS FINISHED\e[0m"
draw_progress_bar 66
# magnum examples ( Debug )
cd ../../magnum-examples
mkdir build
cd build
cmake .. \
    -DCMAKE_INSTALL_PREFIX="$INSTALL_FOLDER" \
    -DCMAKE_PREFIX_PATH="$INSTALL_FOLDER" \
    -D_CORRADE_MODULE_DIR="$INSTALL_FOLDER/share/cmake/Corrade" \
    -DIMGUI_DIR="$DEPENDENCY_FOLDER/imgui" \
    -DWITH_IMGUI_EXAMPLE=ON\
    -DWITH_TRIANGLE_EXAMPLE=OFF
    
make install
draw_progress_bar 70
# MAKE MPFLUID

# Make VRPN
cd ../../vrpn
mkdir build
cd build 
cmake -DCMAKE_INSTALL_PREFIX=$INSTALL_FOLDER .. 
draw_progress_bar 73
make -j
make install 
echo -e "\e[46mvrpn IS FINISHED\e[0m"
draw_progress_bar 77

echo -e "\e[41mSynch INTEGRATION IS BUILDING\e[0m"
# Make Synch
cd ../../synch_fixed/synch
mkdir build
cd build
cmake .. \
    -DCMAKE_INSTALL_PREFIX="$INSTALL_FOLDER" \
    -DCMAKE_PREFIX_PATH="$INSTALL_FOLDER" \
    -DVRPN_ROOT_DIR="$INSTALL_FOLDER/lib/vrpn"

make install
echo -e "\e[46msynch IS FINISHED\e[0m"
draw_progress_bar 83

echo -e "\e[41mmpfluid_vis_sari INTEGRATION IS BUILDING\e[0m"

# Make MPfluid
cd $CWD/mpfluid_vis_sari
mkdir build
cd build
cmake ../src \
    -DCMAKE_INSTALL_PREFIX="$INSTALL_FOLDER"/mpfluid \
    -DCMAKE_PREFIX_PATH="$INSTALL_FOLDER" \
    -DUSE_HDF5=OFF\
    -DBUILD_HDF_CLIENT=OFF\
    -Dsynch_DIR=$INSTALL_FOLDER/"cmake" \
    -DUSE_SDL2=OFF\
    -D_CORRADE_MODULE_DIR="$INSTALL_FOLDER/share/cmake/Corrade" \
    -DBUILD_SW_CLIENT=OFF\
    -DUSE_SWCOLLECTOR=ON\
    -DUSE_VTK=ON\
    -DBUILD_SW_CLIENT=ON\
    -DBUILD_SCENOGRAPH_PROJECT=ON\
    -DImGui_INCLUDE_DIR="$DEPENDENCY_FOLDER/imgui" 
draw_progress_bar 88
make 
draw_progress_bar 96
make install
# 
echo "export LD_LIBRARY_PATH=:$INSTALL_FOLDER/lib:$LD_LIBRARY_PATH">> ~/.bashrc
draw_progress_bar 99
echo -e "\e[44mBuilding libraries finished\e[0m"
destroy_scroll_area
