#!/bin/bash

#   sariug
#   Current Update : 26.06.2019
#

GLFW3=3.2
GLM=0.9.7.0
OPENMPI=openmpi-2.1.0
VTK=VTK-8.2.0
# Create source code directory
mkdir source
# Get to Source directory
cd source
# Check for SDL2 ( is used mostly for debugging and ensuring magnum works good)
if ldconfig -p | grep libsdl2; then
echo "SDL2 found in usr"
else
echo "SDL2 not found in usr, installing"
    if [ -d "SDL2-2.0.9" ]; then
        echo "SDL2 folder exist"
    else
    wget 'https://www.libsdl.org/release/SDL2-2.0.9.tar.gz'
    tar -xvf 'SDL2-2.0.9.tar.gz'
    rm $'SDL2-2.0.9.tar.gz'
    fi
fi


# Download Corrade
if [ -d "corrade" ]; then
    echo "Corrade exist"
else
git clone https://github.com/mosra/corrade.git
cd corrade
git checkout 150d3972d6047ddfd4685a76b45195a23d57efea
cd ..
fi

# Download Magnum
if [ -d "magnum" ]; then
    echo "magnum exist"
else
git clone https://github.com/mosra/magnum.git
cd magnum
git checkout d557563a838837595cb8208eb9398e9ebbee7baa
cd ..
fi

# Download Magnum Integration
if [ -d "magnum-integration" ]; then
    echo "magnum exist"
else
git clone https://github.com/mosra/magnum-integration.git
cd magnum-integration
git checkout 2cde27dbf3f00ac829d77a2e7ff094e3cf76b904
cd ..
fi
# Download Magnum Plugins
# git clone https://github.com/mosra/magnum-plugins.git

# Download glfw3
if [ -d "glfw-$GLFW3" ]; then
    echo "GLFW $GLFW3 exist"
else 
    wget 'https://github.com/glfw/glfw/archive/3.2.zip'
    unzip $GLFW3
    rm $GLFW3*
fi

# Download glm
if [ -d "glm-$GLM" ]; then
    echo "GLM $GLM exist"
else 
    wget 'https://github.com/g-truc/glm/archive/0.9.7.0.zip'
    unzip $GLM
    rm $GLM*
fi

# Download imgui
if [ -d "imgui" ]; then
    echo "GLM $GLM exist"
else
    git clone https://github.com/ocornut/imgui.git
    cd imgui
    git checkout b8fe0df7df79dcf7560246f9c3510f5e54de6ff6
    cd ..
fi
# Download Openmpi
if [ -d "$OPENMPI" ]; then
    echo "$OPENMPI exist"
else 
    wget 'https://download.open-mpi.org/release/open-mpi/v2.1/openmpi-2.1.0.tar.gz'
    tar -xvf $OPENMPI.tar.gz
    rm $OPENMPI.tar.gz
fi

# Download vtk
if [ -d "$VTK" ]; then
    echo "$VTK exist"
else 
    wget 'https://www.vtk.org/files/release/8.2/VTK-8.2.0.zip'
    unzip $VTK.zip
    rm $VTK.zip
fi

# Magnum examples (for Debug)
git clone https://github.com/mosra/magnum-examples.git

