#!/bin/bash
GLFW3=3.2
GLM=0.9.7.0
OPENMPI=openmpi-2.1.0
VTK=VTK-8.2.0
# Create source code directory
mkdir source
# Get to Source directory
cd source

# Download Corrade
git clone https://github.com/mosra/corrade.git

# Download Magnum
git clone https://github.com/mosra/magnum.git

# Download Magnum Integration
git clone https://github.com/mosra/magnum-integration.git

# Download Magnum Plugins
git clone https://github.com/mosra/magnum-plugins.git

# Download glfw3
if [ -d "glfw-$GLFW3" ]; then
    echo "GLFW $GLFW3 exist"
else 
    wget 'https://github.com/glfw/glfw/archive/3.2.zip'
    unzip $GLFW3
    rm $GLFW3
fi

# Download glm
if [ -d "glm-$GLM" ]; then
    echo "GLM $GLM exist"
else 
    wget 'https://github.com/g-truc/glm/archive/0.9.7.0.zip'
    unzip $GLM
    rm $GLM
fi

# Download imgui
git clone https://github.com/ocornut/imgui.git

# Download Openmpi
if [ -d "$OPENMPI" ]; then
    echo "$OPENMPI exist"
else 
    wget 'https://download.open-mpi.org/release/open-mpi/v2.1/openmpi-2.1.0.tar.gz'
    tar -xvf $OPENMPI.tar.gz
    rm $OPENMPI.tar.gz
fi

# Download vtk
if [ -d "$VTK" ]; then
    echo "$VTK exist"
else 
    wget 'https://www.vtk.org/files/release/8.2/VTK-8.2.0.zip'
    unzip $VTK.zip
    rm $VTK.zip
fi

# Magnum examples (for Debug)
git clone https://github.com/mosra/magnum-examples.git

